# frozen_string_literal: true
source 'https://supermarket.chef.io'

cookbook 'apt', '~> 7.0.0'

cookbook 'nginx', '~> 8.1.5'

cookbook 'nodejs', '= 2.0.0'

cookbook 'redis', '~> 3.0.4'

cookbook 'chef-ruby', '~> 0.1.2'

# cookbook 'postgresql', '~> 7.1.0'
# cookbook 'elasticsearch', '~> 4.0.1'
